name: 🌱 Deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: |
            ./.markata.cache
            ./markout
          key: ${{ runner.os }}-${{ hashfiles('markata.toml') }}-markata-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ hashfiles('markata.toml') }}-markata-${{ github.sha }}-
            ${{ runner.os }}-${{ hashfiles('markata.toml') }}-markata-
            ${{ runner.os }}-${{ hashfiles('markata.toml') }}-
            ${{ runner.os }}-
      - name: did cache restore?
        run: ls markout

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install markata
        run: pip install -r requirements.txt

      - name: run markata
        run: markata build --no-pretty

      - name: create root
        run: |
            cp static/index.html markout/index.html

      - name: GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: markout
          build_dir: markout
          jekyll: false
